/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avance_de_proyecto;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author diego
 */
public class Gui_del_proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Gui_del_proyecto
     */
    public Gui_del_proyecto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_archivo = new javax.swing.JDialog();
        jb_cerrararchivo = new javax.swing.JButton();
        jb_salirdemenucampos = new javax.swing.JButton();
        BTN_CrearCampos = new javax.swing.JButton();
        BTN_ModificarCampos = new javax.swing.JButton();
        BTN_ListarCampos = new javax.swing.JButton();
        BTN_BorrarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_guardararchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        JD_CrearCampos = new javax.swing.JDialog();
        jP_crear_campos = new javax.swing.JPanel();
        btn_cancelar_crear_campos = new javax.swing.JButton();
        BTN_Regresar = new javax.swing.JButton();
        TF_NombreCampo = new javax.swing.JTextField();
        SP_TamañoMinimo = new javax.swing.JSpinner();
        SP_TamañoMaximo = new javax.swing.JSpinner();
        CB_TipoDeDato = new javax.swing.JComboBox<>();
        RB_LlavePrimariaSi = new javax.swing.JRadioButton();
        RB_LlavePrimariaNo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        JD_ModificarCampos = new javax.swing.JDialog();
        jP_modificar_campos = new javax.swing.JPanel();
        btn_cerrar_modificar_campos = new javax.swing.JButton();
        btn_cancelar_modificar_campos = new javax.swing.JButton();
        btn_listar_campos_desde_modificar = new javax.swing.JButton();
        JD_ListarCampos = new javax.swing.JDialog();
        jP_listar_campos = new javax.swing.JPanel();
        btn_actualizar_listar_campos = new javax.swing.JButton();
        btn_cerrar_listar_campos = new javax.swing.JButton();
        JD_BorrarCampos = new javax.swing.JDialog();
        jP_borrar_campos = new javax.swing.JPanel();
        btn_borrar_campos = new javax.swing.JButton();
        btn_cancelar_borrar_campos = new javax.swing.JButton();
        btn_cerrar_borrar_campos = new javax.swing.JButton();
        jb_nuevoarchvo = new java.awt.Button();
        jb_abrrarchivo = new java.awt.Button();
        jb_salir = new java.awt.Button();

        jb_cerrararchivo.setText("Cerrar Archivo");
        jb_cerrararchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cerrararchivoMouseClicked(evt);
            }
        });

        jb_salirdemenucampos.setText("Salir");
        jb_salirdemenucampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirdemenucamposMouseClicked(evt);
            }
        });
        jb_salirdemenucampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirdemenucamposActionPerformed(evt);
            }
        });

        BTN_CrearCampos.setText("Crear Campos");
        BTN_CrearCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CrearCamposActionPerformed(evt);
            }
        });

        BTN_ModificarCampos.setText("Modificar Campos");
        BTN_ModificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModificarCamposActionPerformed(evt);
            }
        });

        BTN_ListarCampos.setText("Listar Campos");
        BTN_ListarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ListarCamposActionPerformed(evt);
            }
        });

        BTN_BorrarCampos.setText("Borrar Campos");
        BTN_BorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BorrarCamposActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu de Campos");

        jb_guardararchivo.setText("Salvar Archivo");
        jb_guardararchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardararchivoMouseClicked(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout jd_archivoLayout = new javax.swing.GroupLayout(jd_archivo.getContentPane());
        jd_archivo.getContentPane().setLayout(jd_archivoLayout);
        jd_archivoLayout.setHorizontalGroup(
            jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_archivoLayout.createSequentialGroup()
                .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_archivoLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jb_salirdemenucampos))
                    .addGroup(jd_archivoLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_CrearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jb_guardararchivo)
                                .addComponent(jb_cerrararchivo)
                                .addComponent(BTN_ModificarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_archivoLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1))
                                .addComponent(BTN_ListarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_BorrarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_archivoLayout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        jd_archivoLayout.setVerticalGroup(
            jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_archivoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_archivoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_CrearCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_ModificarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_ListarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_BorrarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_guardararchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_cerrararchivo)
                        .addGap(64, 64, 64))
                    .addGroup(jd_archivoLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jb_salirdemenucampos)
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(jd_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_archivoLayout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        jP_crear_campos.setBackground(new java.awt.Color(255, 255, 255));

        btn_cancelar_crear_campos.setText("Cancelar");

        BTN_Regresar.setText("Regresar");

        TF_NombreCampo.setText("jTextField1");

        CB_TipoDeDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "byte", "short", "double", "float", "long", "char", "string", "boolean" }));

        RB_LlavePrimariaSi.setText("SI");

        RB_LlavePrimariaNo.setText("NO");

        jButton1.setText("Crear Campo");

        javax.swing.GroupLayout jP_crear_camposLayout = new javax.swing.GroupLayout(jP_crear_campos);
        jP_crear_campos.setLayout(jP_crear_camposLayout);
        jP_crear_camposLayout.setHorizontalGroup(
            jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_crear_camposLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_crear_camposLayout.createSequentialGroup()
                        .addComponent(RB_LlavePrimariaSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RB_LlavePrimariaNo))
                    .addComponent(CB_TipoDeDato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_NombreCampo)
                    .addGroup(jP_crear_camposLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SP_TamañoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SP_TamañoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(jP_crear_camposLayout.createSequentialGroup()
                .addGroup(jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_crear_camposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_Regresar))
                    .addGroup(jP_crear_camposLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar_crear_campos)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jP_crear_camposLayout.setVerticalGroup(
            jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_crear_camposLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TF_NombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_TipoDeDato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SP_TamañoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_TamañoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_LlavePrimariaSi)
                    .addComponent(RB_LlavePrimariaNo))
                .addGap(62, 62, 62)
                .addGroup(jP_crear_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_cancelar_crear_campos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(BTN_Regresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_CrearCamposLayout = new javax.swing.GroupLayout(JD_CrearCampos.getContentPane());
        JD_CrearCampos.getContentPane().setLayout(JD_CrearCamposLayout);
        JD_CrearCamposLayout.setHorizontalGroup(
            JD_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_crear_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_CrearCamposLayout.setVerticalGroup(
            JD_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_crear_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jP_modificar_campos.setBackground(new java.awt.Color(0, 204, 255));

        btn_cerrar_modificar_campos.setText("Cerrar");

        btn_cancelar_modificar_campos.setText("Cancelar");

        btn_listar_campos_desde_modificar.setText("Listar Campos");

        javax.swing.GroupLayout jP_modificar_camposLayout = new javax.swing.GroupLayout(jP_modificar_campos);
        jP_modificar_campos.setLayout(jP_modificar_camposLayout);
        jP_modificar_camposLayout.setHorizontalGroup(
            jP_modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_modificar_camposLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(btn_cancelar_modificar_campos)
                .addGap(27, 27, 27)
                .addComponent(btn_cerrar_modificar_campos)
                .addGap(42, 42, 42)
                .addComponent(btn_listar_campos_desde_modificar)
                .addGap(44, 44, 44))
        );
        jP_modificar_camposLayout.setVerticalGroup(
            jP_modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_modificar_camposLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addGroup(jP_modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cerrar_modificar_campos)
                    .addComponent(btn_cancelar_modificar_campos)
                    .addComponent(btn_listar_campos_desde_modificar))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout JD_ModificarCamposLayout = new javax.swing.GroupLayout(JD_ModificarCampos.getContentPane());
        JD_ModificarCampos.getContentPane().setLayout(JD_ModificarCamposLayout);
        JD_ModificarCamposLayout.setHorizontalGroup(
            JD_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_modificar_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ModificarCamposLayout.setVerticalGroup(
            JD_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModificarCamposLayout.createSequentialGroup()
                .addComponent(jP_modificar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jP_listar_campos.setBackground(new java.awt.Color(0, 204, 255));

        btn_actualizar_listar_campos.setText("Actualizar");

        btn_cerrar_listar_campos.setText("Cerrar");

        javax.swing.GroupLayout jP_listar_camposLayout = new javax.swing.GroupLayout(jP_listar_campos);
        jP_listar_campos.setLayout(jP_listar_camposLayout);
        jP_listar_camposLayout.setHorizontalGroup(
            jP_listar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listar_camposLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btn_cerrar_listar_campos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btn_actualizar_listar_campos)
                .addGap(74, 74, 74))
        );
        jP_listar_camposLayout.setVerticalGroup(
            jP_listar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listar_camposLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(jP_listar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar_listar_campos)
                    .addComponent(btn_cerrar_listar_campos))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout JD_ListarCamposLayout = new javax.swing.GroupLayout(JD_ListarCampos.getContentPane());
        JD_ListarCampos.getContentPane().setLayout(JD_ListarCamposLayout);
        JD_ListarCamposLayout.setHorizontalGroup(
            JD_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_listar_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ListarCamposLayout.setVerticalGroup(
            JD_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_listar_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jP_borrar_campos.setBackground(new java.awt.Color(0, 204, 255));

        btn_borrar_campos.setText("Borrar Campo(s)");

        btn_cancelar_borrar_campos.setText("Cancelar");

        btn_cerrar_borrar_campos.setText("Cerrar");

        javax.swing.GroupLayout jP_borrar_camposLayout = new javax.swing.GroupLayout(jP_borrar_campos);
        jP_borrar_campos.setLayout(jP_borrar_camposLayout);
        jP_borrar_camposLayout.setHorizontalGroup(
            jP_borrar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_borrar_camposLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_cancelar_borrar_campos)
                .addGap(39, 39, 39)
                .addComponent(btn_cerrar_borrar_campos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btn_borrar_campos)
                .addGap(52, 52, 52))
        );
        jP_borrar_camposLayout.setVerticalGroup(
            jP_borrar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_borrar_camposLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addGroup(jP_borrar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_borrar_campos)
                    .addComponent(btn_cancelar_borrar_campos)
                    .addComponent(btn_cerrar_borrar_campos))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout JD_BorrarCamposLayout = new javax.swing.GroupLayout(JD_BorrarCampos.getContentPane());
        JD_BorrarCampos.getContentPane().setLayout(JD_BorrarCamposLayout);
        JD_BorrarCamposLayout.setHorizontalGroup(
            JD_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BorrarCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_borrar_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_BorrarCamposLayout.setVerticalGroup(
            JD_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_borrar_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("principal");
        setName("principal"); // NOI18N

        jb_nuevoarchvo.setLabel("Nuevo Archivo");
        jb_nuevoarchvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoarchvoMouseClicked(evt);
            }
        });
        jb_nuevoarchvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoarchvoActionPerformed(evt);
            }
        });

        jb_abrrarchivo.setLabel("Abrir Archivo");
        jb_abrrarchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrrarchivoMouseClicked(evt);
            }
        });

        jb_salir.setLabel("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_abrrarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_nuevoarchvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jb_nuevoarchvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_abrrarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_nuevoarchvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoarchvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_nuevoarchvoActionPerformed

    private void jb_salirdemenucamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirdemenucamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salirdemenucamposActionPerformed

    private void BTN_BorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BorrarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_BorrarCamposActionPerformed

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_nuevoarchvoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoarchvoMouseClicked
        // TODO add your handling code here:
        JFileChooser guardarcomo = new JFileChooser();
        guardarcomo.setApproveButtonText("Guardar");
        guardarcomo.showSaveDialog(null);
        File archivo = new File(guardarcomo.getSelectedFile() + ".txt");
        try {
            BufferedWriter salida = new BufferedWriter(new FileWriter(archivo));
            salida.write("Prueba a ver s abre esta mierda");
            salida.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_nuevoarchvoMouseClicked

    private void jb_abrrarchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrrarchivoMouseClicked
        // TODO add your handling code here:
        fichero = null;//Este fichero esta definido como una variable global en la linea 370 debido que ocupo mantener el archivo para guardar
        FileReader fr = null;
        BufferedReader br = null;
        jTextArea2.setText("");
        try {
            JFileChooser filechooser = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
            FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp");
            filechooser.setFileFilter(filtro);
            filechooser.addChoosableFileFilter(filtro2);
            int seleccion = filechooser.showOpenDialog(null);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = filechooser.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                jTextArea2.setText("");
                while ((linea = br.readLine()) != null) {
                    jTextArea2.append(linea);
                    jTextArea2.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        jd_archivo.pack();
        jd_archivo.setLocationRelativeTo(null);
        jd_archivo.setVisible(true);
    }//GEN-LAST:event_jb_abrrarchivoMouseClicked

    private void jb_guardararchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardararchivoMouseClicked
        // TODO add your handling code here:
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(fichero);
            bw = new BufferedWriter(fw);
            bw.write(jTextArea2.getText());
            jTextArea2.setText(jTextArea2.getText());
            bw.flush();
            JOptionPane.showMessageDialog(null, "Archivo Guardado Exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_guardararchivoMouseClicked

    private void jb_salirdemenucamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirdemenucamposMouseClicked
        // TODO add your handling code here:
        jd_archivo.setVisible(false);
        String opcion_deguardado = JOptionPane.showInputDialog(null, "Desea guardarlo (SI o NO)?");//Este string solo se utiliza para saber si lo quiere guardar antes de cerrar el archivo
        if (opcion_deguardado.equals("SI") || opcion_deguardado.equals("Si") || opcion_deguardado.equals("si") || opcion_deguardado.equals("NO") || opcion_deguardado.equals("No") || opcion_deguardado.equals("no")) {
            if (opcion_deguardado.equals("SI") || opcion_deguardado.equals("Si") || opcion_deguardado.equals("si")) {
                FileWriter fw = null;
                BufferedWriter bw = null;
                try {
                    fw = new FileWriter(fichero);
                    bw = new BufferedWriter(fw);
                    bw.write(jTextArea2.getText());
                    jTextArea2.setText("");
                    bw.flush();
                    JOptionPane.showMessageDialog(null, "Archivo Guardado Exitosamente");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                jd_archivo.setVisible(false);
            } else {
                jd_archivo.setVisible(false);
            }
        } else {
            jd_archivo.setVisible(false);
        }
    }//GEN-LAST:event_jb_salirdemenucamposMouseClicked

    private void jb_cerrararchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cerrararchivoMouseClicked
        // TODO add your handling code here:
        String opcion_deguardado = JOptionPane.showInputDialog(this, "Desea guardarlo (SI o NO)?");//Este string solo se utiliza para saber si lo quiere guardar antes de cerrar el archivo
        if (opcion_deguardado.equals("SI") || opcion_deguardado.equals("Si") || opcion_deguardado.equals("si") || opcion_deguardado.equals("NO") || opcion_deguardado.equals("No") || opcion_deguardado.equals("no")) {
            if (opcion_deguardado.equals("SI") || opcion_deguardado.equals("Si") || opcion_deguardado.equals("si")) {
                FileWriter fw = null;
                BufferedWriter bw = null;
                try {
                    fw = new FileWriter(fichero);
                    bw = new BufferedWriter(fw);
                    bw.write(jTextArea2.getText());
                    jTextArea2.setText("");
                    bw.flush();
                    JOptionPane.showMessageDialog(this, "Archivo Guardado Exitosamente");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                jd_archivo.setVisible(false);
            } else {
                jd_archivo.setVisible(false);
            }
        } else {
            jd_archivo.setVisible(false);
        }
    }//GEN-LAST:event_jb_cerrararchivoMouseClicked

    private void BTN_CrearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CrearCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CrearCamposActionPerformed

    private void BTN_ModificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ModificarCamposActionPerformed

    private void BTN_ListarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ListarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ListarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_del_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_del_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_del_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_del_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_del_proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BorrarCampos;
    private javax.swing.JButton BTN_CrearCampos;
    private javax.swing.JButton BTN_ListarCampos;
    private javax.swing.JButton BTN_ModificarCampos;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JComboBox<String> CB_TipoDeDato;
    private javax.swing.JDialog JD_BorrarCampos;
    private javax.swing.JDialog JD_CrearCampos;
    private javax.swing.JDialog JD_ListarCampos;
    private javax.swing.JDialog JD_ModificarCampos;
    private javax.swing.JRadioButton RB_LlavePrimariaNo;
    private javax.swing.JRadioButton RB_LlavePrimariaSi;
    private javax.swing.JSpinner SP_TamañoMaximo;
    private javax.swing.JSpinner SP_TamañoMinimo;
    private javax.swing.JTextField TF_NombreCampo;
    private javax.swing.JButton btn_actualizar_listar_campos;
    private javax.swing.JButton btn_borrar_campos;
    private javax.swing.JButton btn_cancelar_borrar_campos;
    private javax.swing.JButton btn_cancelar_crear_campos;
    private javax.swing.JButton btn_cancelar_modificar_campos;
    private javax.swing.JButton btn_cerrar_borrar_campos;
    private javax.swing.JButton btn_cerrar_listar_campos;
    private javax.swing.JButton btn_cerrar_modificar_campos;
    private javax.swing.JButton btn_listar_campos_desde_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_borrar_campos;
    private javax.swing.JPanel jP_crear_campos;
    private javax.swing.JPanel jP_listar_campos;
    private javax.swing.JPanel jP_modificar_campos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Button jb_abrrarchivo;
    private javax.swing.JButton jb_cerrararchivo;
    private javax.swing.JButton jb_guardararchivo;
    private java.awt.Button jb_nuevoarchvo;
    private java.awt.Button jb_salir;
    private javax.swing.JButton jb_salirdemenucampos;
    private javax.swing.JDialog jd_archivo;
    // End of variables declaration//GEN-END:variables
private File fichero;
}
